# Short Burst Analysis

Read result files from Short Burst run and prints the max score found for each run and the minority's VAP population found for the partition with the best score in the run:

In [5]:
import numpy as np
import pickle
import os

for file_name in os.listdir("data_sb/"):
    print(f"\n\nFile = {file_name}")
    if file_name.endswith(".npy"):
        res = np.load(f"data_sb/{file_name}")
        print(res)
        print(f"Max Number of Opp Districts: {np.max(res)}")

    else:
        with open(f"data_sb/{file_name}", "rb") as file:
            max_stats = pickle.load(file)
            print(max_stats["AMINVAP"])
            print(f"Max Stats = {max([max_stats["AMINVAP"][key] for key in max_stats["AMINVAP"].keys()])}")



File = ND_dists47_AMINVAPopt_5.0%_40000_sbl10_scorenum_opportunity_dists_0.4.npy
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Max Number of Opp Districts: 1.0


File = ND_dists47_AMINVAPopt_5.0%_40000_sbl10_scorenum_opportunity_dists_0.4.p
{'9': 92, '38': 216, '4': 223, '5': 744, '3': 277, '40': 125, '29': 187, '26': 422, '6': 157, '2': 95, '19': 388, '39': 1265, '1': 555, '23': 160, '36': 123, '28': 1383, '14': 96, '33': 793, '20': 77, '24': 370, '17': 245, '15': 398, '35': 375, '8': 195, '18': 236, '31': 328, '34': 1691, '12': 756, '25': 377, '42': 442, '32': 228, '7': 236, '22': 5902, '27': 99, '16': 182, '45': 128, '10': 101, '21': 106, '13': 162, '41': 383, '46': 2012, '44': 676, '37': 301, '47': 134, '30': 261, '43': 580, '11': 723}
Max Stats = 5902


File = ND_dists47_AMINVAPopt_5.0%_40000_sbl10_scorenum_opportunity_dists_0.45.npy
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. .