In [38]:
import numpy as np
import pickle
import os

for file_name in os.listdir("data_sb/"):
    print(f"\n\nFile = {file_name}")
    if file_name.endswith(".npy"):
        res = np.load(f"data_sb/{file_name}")
        print(res)
        print(f"Max Score: {np.max(res)}")

    else:
        with open("data_sb/ND_dists47_AMINVAPopt_5.0%_40000_sbl15_scorenum_opportunity_dists_0.5.p", "rb") as file:
            max_stats = pickle.load(file)
            print(max_stats["AMINVAP"])
            print(f"Max Stats = {max([max_stats["AMINVAP"][key] for key in max_stats["AMINVAP"].keys()])}")



File = ND_dists47_AMINVAPopt_5.0%_40000_sbl10_scorenum_opportunity_dists_0.4.npy
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]
Max Score: 1.0


File = ND_dists47_AMINVAPopt_5.0%_40000_sbl10_scorenum_opportunity_dists_0.4.p
{'9': 128, '38': 197, '4': 221, '5': 136, '3': 112, '40': 625, '29': 104, '26': 201, '6': 280, '2': 252, '19': 159, '39': 2682, '1': 999, '23': 336, '36': 2029, '28': 429, '14': 228, '33': 528, '20': 308, '24': 455, '17': 265, '15': 69, '35': 598, '8': 141, '18': 204, '31': 89, '34': 326, '12': 488, '25': 431, '42': 2219, '32': 279, '7': 48, '22': 70, '27': 224, '16': 454, '45': 329, '10': 184, '21': 86, '13': 131, '41': 102, '46': 788, '44': 5902, '37': 165, '47': 244, '30': 102, '43': 419, '11': 239}
Max Stats = 5902


File = ND_dists47_AMINVAPopt_5.0%_40000_sbl10_scorenum_opportunity_dists_0.45.npy
[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1